version: '2'
services:
    nginx:
        image: nginx:1.12
        depends_on:
            - php
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "127.0.144.10:80:80"
    php:
        build:
            dockerfile: Dockerfile
            context: ./docker
        volumes:
             - .:/var/www/html
    mysql:
        image: mysql:5.7
        environment:
          - MYSQL_RANDOM_ROOT_PASSWORD=true
          - MYSQL_DATABASE=pm
          - MYSQL_USER=dev
          - MYSQL_PASSWORD=dev